export const theme = {
  light: {
    bgPage: 'bg-slate-50',
    bgPanel: 'bg-white',
    card: 'bg-white',
    cardSoft: 'bg-slate-50',
    border: 'border-slate-200',
    text: 'text-slate-900',
    textMuted: 'text-slate-500',
    textSubtle: 'text-slate-400',
    navActive: 'bg-slate-900 text-white',
    navInactive: 'text-slate-700 hover:bg-slate-100',
    navIconActive: 'bg-white text-slate-900',
    navIconInactive: 'bg-slate-200 text-slate-700',
    chip: 'bg-slate-900 text-white',
    buttonPrimary: 'bg-slate-900 text-white border-slate-900 hover:bg-black',
    buttonGhost: 'bg-white text-slate-900 border-slate-200 hover:border-slate-400',
    buttonOutline: 'bg-white text-slate-900 border-slate-200 hover:border-slate-400',
  },
  dark: {
    bgPage: 'bg-[#0b0e13]',
    bgPanel: 'bg-[#0e1117]',
    card: 'bg-white/5',
    cardSoft: 'bg-white/5',
    border: 'border-white/10',
    text: 'text-white',
    textMuted: 'text-slate-400',
    textSubtle: 'text-slate-500',
    navActive: 'bg-white text-black',
    navInactive: 'text-slate-300 hover:bg-white/10',
    navIconActive: 'bg-black text-white',
    navIconInactive: 'bg-white/10 text-slate-200',
    chip: 'bg-white text-black',
    buttonPrimary: 'bg-white text-black border-white hover:bg-slate-200',
    buttonGhost: 'bg-transparent text-white border-white/30 hover:border-white',
    buttonOutline: 'bg-transparent text-white border-white/30 hover:border-white',
  },
}

export const getTheme = (mode) => theme[mode] || theme.light
